version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-platino
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    command: ["serve"]

  db:
    image: postgres:15
    container_name: platino-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  qdrant:
    image: qdrant/qdrant
    container_name: platino-qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build:
      context: ./platino-backend
    container_name: platino-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    volumes:
      - ./platino-backend:/app
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - QDRANT_URL=${QDRANT_URL}
    depends_on:
      - db
      - ollama
      - qdrant

  # frontend:
  #   build:
  #     context: ./platino-frontend
  #   container_name: platino-frontend
  #   command: npm run dev -- --host
  #   volumes:
  #     - ./platino-frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "${FRONTEND_PORT}:5173"
  #   depends_on:
  #     - backend

volumes:
  ollama_models:
  postgres_data:
  qdrant_data:
